<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

	  <PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>true</SelfContained>
	  <!-- includes .NET runtime -->
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <!-- or linux-x64, osx-x64 -->
	  <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	  <PublishTrimmed>true</PublishTrimmed>
	  <!-- optional, reduces file size -->
  </PropertyGroup>

  <ItemGroup>
    <None Remove="model.yaml" />
    <None Remove="Resources\ProgramTemplate" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="model.yaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="Resources\IRepositoryTemplate">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="Resources\ProgramTemplate">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="Resources\RepositoryTemplate">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


	<ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackendGenerator.Core\BackendGenerator.Core.csproj" />
    <ProjectReference Include="..\BackendGenerator.Infrastructure\BackendGenerator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
